/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package f2_proyecto_estructuras;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.LinkedList;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Pantalla_Cliente extends javax.swing.JFrame {
    
    private ImageIcon imagen;
    private Icon icono;
    Lista_Ad lista;
    int opcion = -1;
    String tipo_recorrido = "";
    LinkedList<Usuario> usuarios;
    TablaHash tabla;
    
    
    public Pantalla_Cliente(LinkedList<Usuario> usuarios, Lista_Ad lista, TablaHash tabla) {
        this.usuarios = usuarios;
        this.lista = lista;
        this.tabla = tabla;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones_grupo = new javax.swing.ButtonGroup();
        Panel_superior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton_Usuarios = new javax.swing.JButton();
        Repo = new javax.swing.JButton();
        Boton_mensajeros = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Boton_lugares = new javax.swing.JButton();
        Boton_rutas = new javax.swing.JButton();
        Panel_visualizacion = new javax.swing.JPanel();
        Label_img = new javax.swing.JLabel();
        Panel_generar_img = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Grafo = new javax.swing.JRadioButton();
        Boton_merkle = new javax.swing.JRadioButton();
        Hash = new javax.swing.JRadioButton();
        Boton_generar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Boton_Actualizar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Lista_A = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel1.setText("Carga Masiva");

        Boton_Usuarios.setText("Usuarios");
        Boton_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_UsuariosActionPerformed(evt);
            }
        });

        Repo.setText("Reporte");
        Repo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepoActionPerformed(evt);
            }
        });

        Boton_mensajeros.setText("Mensajeros");
        Boton_mensajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_mensajerosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel2.setText("Otras Opciones");

        Boton_lugares.setText("Lugares");
        Boton_lugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_lugaresActionPerformed(evt);
            }
        });

        Boton_rutas.setText("Rutas");
        Boton_rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_rutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_superiorLayout = new javax.swing.GroupLayout(Panel_superior);
        Panel_superior.setLayout(Panel_superiorLayout);
        Panel_superiorLayout.setHorizontalGroup(
            Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_superiorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59))
                    .addGroup(Panel_superiorLayout.createSequentialGroup()
                        .addComponent(Boton_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_mensajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_lugares, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(Repo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        Panel_superiorLayout.setVerticalGroup(
            Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Usuarios)
                    .addComponent(Boton_mensajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_lugares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Repo)
                    .addComponent(Boton_rutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel_visualizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Panel_visualizacionLayout = new javax.swing.GroupLayout(Panel_visualizacion);
        Panel_visualizacion.setLayout(Panel_visualizacionLayout);
        Panel_visualizacionLayout.setHorizontalGroup(
            Panel_visualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_visualizacionLayout.createSequentialGroup()
                .addComponent(Label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );
        Panel_visualizacionLayout.setVerticalGroup(
            Panel_visualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_visualizacionLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(Label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel3.setText("Estructuras ");

        Botones_grupo.add(Grafo);
        Grafo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Grafo.setText("Grafo");
        Grafo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrafoMouseClicked(evt);
            }
        });

        Botones_grupo.add(Boton_merkle);
        Boton_merkle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Boton_merkle.setText("Arbol Merkle");
        Boton_merkle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_merkleMouseClicked(evt);
            }
        });

        Botones_grupo.add(Hash);
        Hash.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Hash.setText("Tabla Hash Mensajeros");
        Hash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HashMouseClicked(evt);
            }
        });
        Hash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HashActionPerformed(evt);
            }
        });

        Boton_generar.setText("Generar");
        Boton_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_generarActionPerformed(evt);
            }
        });

        jLabel7.setText("Bloque");

        Boton_Actualizar.setText("Actualizar");
        Boton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ActualizarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel8.setText("Modificaciones");

        Botones_grupo.add(Lista_A);
        Lista_A.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Lista_A.setText("Lista de Adyacencia ");
        Lista_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_AMouseClicked(evt);
            }
        });
        Lista_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_generar_imgLayout = new javax.swing.GroupLayout(Panel_generar_img);
        Panel_generar_img.setLayout(Panel_generar_imgLayout);
        Panel_generar_imgLayout.setHorizontalGroup(
            Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hash)
                            .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                                .addComponent(Boton_merkle)
                                .addGap(166, 166, 166)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Grafo)
                            .addComponent(Lista_A)))
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(Boton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8))
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_generar_imgLayout.setVerticalGroup(
            Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(Hash)
                .addGap(18, 18, 18)
                .addComponent(Grafo)
                .addGap(18, 18, 18)
                .addComponent(Lista_A)
                .addGap(17, 17, 17)
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_merkle))
                .addGap(32, 32, 32)
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jLabel8)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_generar_img, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Panel_visualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Panel_generar_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Panel_visualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HashActionPerformed

    private void Boton_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_UsuariosActionPerformed
        // CARGA MASIVA Usuarios
        
        
        
        //creando un nuevo objeto de tipo FileChooser
        JFileChooser fc = new JFileChooser();
        //el op guardará la seleccion del filechooser, si acepta o cancela
        int op = fc.showOpenDialog(this); 
        // Si el usuario acepta, entonces...
        if(op == JFileChooser.APPROVE_OPTION){
            try {
                String direccion = fc.getSelectedFile().toString();
                System.out.println(direccion);
                //ruta_chooser = true;
                
                Lector_usuarios lector = new Lector_usuarios(direccion);
                lector.Lectura(usuarios);
                //reporte();
            
                JOptionPane.showMessageDialog(this, "Se ha finalizado la carga masiva de capas"); 
                
            }catch(NumberFormatException e){
                e.printStackTrace();
            }
        }
        
        
        
        

        
        
        
        
        
        

        //usuario.capas.crear_grafo(usuario.capas.raiz);
        //usuario.capas.imprimir();
        //Matriz_pixeles d = usuario.capas.recorrido_Preorden(2);
        //Creador_img f = new Creador_img(d);
        
        
        
        
        //ABB arbol = usuario.capas;
        //arbol.crear_grafo(arbol.raiz);
        //arbol.imprimir();
    }//GEN-LAST:event_Boton_UsuariosActionPerformed

    private void HashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HashMouseClicked
        //Código del radio button
        opcion = 1;
    }//GEN-LAST:event_HashMouseClicked

    private void GrafoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrafoMouseClicked
        // TODO del por imagen
        opcion = 2;
    }//GEN-LAST:event_GrafoMouseClicked

    private void Boton_merkleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_merkleMouseClicked
        // TODO add your handling code here:
        opcion = 3;
    }//GEN-LAST:event_Boton_merkleMouseClicked

    private void Boton_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_generarActionPerformed
    
        System.out.println(tipo_recorrido);
        System.out.println(opcion);
        
        if (opcion == -1){
            JOptionPane.showMessageDialog(this, "Seleccione una opción");
        }else{
            
            switch(opcion){
                
                
                case 1: // Recorrido por límite
                    
                    /*
                    int cantidad = Integer.parseInt(cantidad_text.getText());
                    System.out.println("vvv"+cantidad);
                    System.out.println(usuario.capas.num_nodos);
                    if (cantidad <= usuario.capas.num_nodos){ 
                        
                    switch (tipo_recorrido) {
                        case "PreOrden":
                            Matriz_pixeles d = usuario.capas.recorrido_Preorden(cantidad);
                            Creador_img f = new Creador_img(d);
                            break;
                        case "InOrden":
                        
                            Matriz_pixeles e = usuario.capas.recorrido_Inorden(cantidad);
                            Creador_img g = new Creador_img(e);
                        
                        
                            break;
                        case "PostOrden":
                            Matriz_pixeles l = usuario.capas.recorrido_Postorden(cantidad);
                            Creador_img h = new Creador_img(l);
                        
                        
                            break;
                        
                        
                        default:
                            break;
                        }
                        JOptionPane.showMessageDialog(this, "Se generó la imagen");
                        
                        Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\0.jpg");
                        //Actualizar_img(Label_img,"src/imagenes/0.png");

                    
                    }else{
                       JOptionPane.showMessageDialog(this, "El número de capas excede a las capas registradas");      
                    }
                    
                    
                    break;*/
                case 2:
                    
                    String graf = lista.Grafo();
                    Creador_img q = new Creador_img(graf);
                    JOptionPane.showMessageDialog(this, "Se generó la imagen");
                    Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\0.jpg");

                    break;
                case 3:
                    /*
                    String conjunto = capas_text.getText();
                    
                    
                    if(!"".equals(conjunto)){
                        Matriz_pixeles j = usuario.capas.recorrido_capas(conjunto);
                        Creador_img m = new Creador_img(j);
                        JOptionPane.showMessageDialog(this, "Se generó la imagen");
                        Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\0.jpg");
                    }else{
                        JOptionPane.showMessageDialog(this, "Ingrese las capas a graficar");
                    }
                    */
                    
                    break;   
                case 4:
                    
                    String gra = lista.Grafo_2();
                    Creador_img qw = new Creador_img(gra);
                    JOptionPane.showMessageDialog(this, "Se generó la imagen");
                    Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\0.jpg");

                    break;
            }        
        }
    }//GEN-LAST:event_Boton_generarActionPerformed

    
    
    private void RepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepoActionPerformed
            try {
                File objetofile = new File ("C:\\Users\\usuario\\Desktop\\provisional\\Reportes\\Reporte_.html");
                Desktop.getDesktop().open(objetofile);

            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Archivo no válido");
                System.out.println(ex);
            }
    }//GEN-LAST:event_RepoActionPerformed

    private void Boton_mensajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_mensajerosActionPerformed
        // CARGA MASIVA Mnesajeros
        //creando un nuevo objeto de tipo FileChooser
        JFileChooser fc = new JFileChooser();
        //el op guardará la seleccion del filechooser, si acepta o cancela
        int op = fc.showOpenDialog(this); 
        // Si el usuario acepta, entonces...
        if(op == JFileChooser.APPROVE_OPTION){
            try {
                String direccion = fc.getSelectedFile().toString();
                System.out.println(direccion);
                //ruta_chooser = true;
                
                Lector_mensajeros lector = new Lector_mensajeros(direccion);
                lector.Lectura(tabla);
                tabla.imprimir();
                JOptionPane.showMessageDialog(this, "Se ha finalizado la carga masiva de imágenes");
                
                
            }catch(NumberFormatException e){
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_Boton_mensajerosActionPerformed

    private void Boton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ActualizarActionPerformed
        // TODO add your handling code here:
        Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\0.jpg");
    }//GEN-LAST:event_Boton_ActualizarActionPerformed

    private void Boton_lugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_lugaresActionPerformed
        
        //creando un nuevo objeto de tipo FileChooser
        JFileChooser fc = new JFileChooser();
        //el op guardará la seleccion del filechooser, si acepta o cancela
        int op = fc.showOpenDialog(this); 
        // Si el usuario acepta, entonces...
        if(op == JFileChooser.APPROVE_OPTION){
            try {
                String direccion = fc.getSelectedFile().toString();
                System.out.println(direccion);
                //ruta_chooser = true;
                
                Lector_lugares l = new Lector_lugares(direccion);
                l.Lectura(lista);

                JOptionPane.showMessageDialog(this, "Se ha finalizado la carga masiva de albumes");
                
            }catch(NumberFormatException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Boton_lugaresActionPerformed

    private void Boton_rutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_rutasActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        //el op guardará la seleccion del filechooser, si acepta o cancela
        int op = fc.showOpenDialog(this); 
        // Si el usuario acepta, entonces...
        if(op == JFileChooser.APPROVE_OPTION){
            try {
                String direccion = fc.getSelectedFile().toString();
                System.out.println(direccion);
                //ruta_chooser = true;
                
                Lector_rutas l = new Lector_rutas(direccion);
                l.Lectura(lista);

                JOptionPane.showMessageDialog(this, "Se ha finalizado la carga masiva de albumes");
                lista.imprimir();
                
            }catch(NumberFormatException e){
                e.printStackTrace();
            }
        }
          
        
    }//GEN-LAST:event_Boton_rutasActionPerformed

    private void Lista_AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_AMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_AMouseClicked

    private void Lista_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_AActionPerformed
            
        // TODO add your handling code here:
        opcion = 4;
    }//GEN-LAST:event_Lista_AActionPerformed

    public void Actualizar_img(JLabel Label_img, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(Label_img.getWidth(),Label_img.getHeight(),Image.SCALE_DEFAULT));//Convirtiendo la imagen a un icóno para poder ponerlo en el label
        // alto de la imagen, ancho de la imagen, algoritmo de escalamiento de la imagen
        Label_img.setIcon(this.icono);
        this.repaint();
    }
    
    /*
    
    public void reporte(){
        
        try{
            String ruta = "C:\\Users\\usuario\\Desktop\\provisional\\Reportes\\Reporte_.html";
            PrintWriter writer = new PrintWriter(ruta, "UTF-8");
            
            
            //empezamos a escribir nuestro html
            writer.println("<link href=\"Reporte_muestra.css\" rel=\"stylesheet\">");
            writer.println("<body>");
            writer.println("    <div id=\"wrapper\">");
            writer.println("    <h1>"+usuario.nombre+"</h1>");
            writer.println("    <br>");
            writer.println("    <br>");
            
            writer.println("    <h2>• Capas hoja</h2>");
            writer.println("    <h3> "+usuario.capas.krecorrido_Inorden()+"</h3>");
            writer.println("    <h2>• Profundidad Arbol</h2>");
            writer.println("    <h3>"+usuario.capas.altura+"</h3>");
            writer.println("    <br>");
            writer.println("    <h2>• Recorridos</h2>");
            writer.println("    <table id=\"keywords\" cellspacing=\"0\" cellpadding=\"0\">");
            writer.println("        <thead>");
            writer.println("        <tr>");
            writer.println("            <th><span>Tipo</span></th>");
            writer.println("            <th><span>Recorrido</span></th>");
            writer.println("        </tr>");
            writer.println("        </thead>");
            writer.println("        <tbody>");
            writer.println("        <tr>");
            writer.println("            <td>PreOrden</td>");
            writer.println("            <td>"+usuario.capas.recorrido_Preorden()+"</td>");
            writer.println("        </tr>");
            writer.println("        <tr>");
            writer.println("            <td>InOrden</td>");
            writer.println("            <td>"+usuario.capas.recorrido_Inorden()+"</td>");
            writer.println("        </tr>");
            writer.println("        <tr>");
            writer.println("            <td>PostOrden</td>");
            writer.println("            <td>"+usuario.capas.recorrido_Postorden()+"</td>");
            writer.println("        </tr>");
            writer.println("        </tbody>");
            writer.println("    </table>");
            writer.println("</BODY>");
            writer.println("</HTML>");
            writer.close();
            
    
            }catch (Exception e) {
            e.printStackTrace();
            }
    
    }
    */
    
    
   
    /**
     * @param args the command line arguments
     */
    
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Actualizar;
    private javax.swing.JButton Boton_Usuarios;
    private javax.swing.JButton Boton_generar;
    private javax.swing.JButton Boton_lugares;
    private javax.swing.JButton Boton_mensajeros;
    private javax.swing.JRadioButton Boton_merkle;
    private javax.swing.JButton Boton_rutas;
    public javax.swing.ButtonGroup Botones_grupo;
    private javax.swing.JRadioButton Grafo;
    private javax.swing.JRadioButton Hash;
    private javax.swing.JLabel Label_img;
    private javax.swing.JRadioButton Lista_A;
    private javax.swing.JPanel Panel_generar_img;
    private javax.swing.JPanel Panel_superior;
    private javax.swing.JPanel Panel_visualizacion;
    private javax.swing.JButton Repo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    

}
