/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package f2_proyecto_estructuras;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Pantalla_estructuras_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_estructuras_usuario
     */
    Usuario usuario;
    private ImageIcon imagen;
    private Icon icono;
    int opcion = -1;
    
    
    public Pantalla_estructuras_usuario(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_botones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Panel_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton_enviar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cedes = new javax.swing.JComboBox<>();
        Mensajeros = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel1.setText("Enviar imágenes");

        Boton_enviar.setText("Enviar");
        Boton_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_enviarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cede");

        jLabel8.setText("Mensajero");

        Cedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Mensajeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout Panel_menuLayout = new javax.swing.GroupLayout(Panel_menu);
        Panel_menu.setLayout(Panel_menuLayout);
        Panel_menuLayout.setHorizontalGroup(
            Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_menuLayout.createSequentialGroup()
                .addGroup(Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_menuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boton_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_menuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(Panel_menuLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_menuLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Mensajeros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(Panel_menuLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                        .addComponent(Cedes, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(97, 97, 97))
        );
        Panel_menuLayout.setVerticalGroup(
            Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_menuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Mensajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Boton_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_enviarActionPerformed
       
        if ( opcion != -1){
 
            switch (opcion) {
                case 1:
                    
                    
                    usuario.capas.crear_grafo(usuario.capas.raiz);
                    String dto = usuario.capas.imprimir();
                    Creador_img gen = new Creador_img(dto);
                    //String dto = usuario.capas.crear_grafo(usuario.capas.raiz);
                    //Creador_img cre = new Creador_img(dto);
                    JOptionPane.showMessageDialog(this, "Se generó la imagen");
                    Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\1.jpg");
                    //Actualizar_img(Label_img,"src/imagenes/0.png");
//
                    break;
                case 2:
                    
                    usuario.imagenes.crear_grafo(usuario.imagenes.raiz);
                    String dt = usuario.imagenes.imprimir();
                    Creador_img gend = new Creador_img(dt);
                    //String dto = usuario.capas.crear_grafo(usuario.capas.raiz);
                    //Creador_img cre = new Creador_img(dto);
                    JOptionPane.showMessageDialog(this, "Se generó la imagen");
                    Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\1.jpg");
                    //Actualizar_img(Label_img,"src/imagenes/0.png");

                        
                    break;
                    
                case 3:
                    
                    
                    String id = capa_id_text.getText();
                    if(!"".equals(id)){
                        
                        Matriz_pixeles j = usuario.capas.recorrido_capas(id);
                        Creador_img m = new Creador_img(j,1);
                        JOptionPane.showMessageDialog(this, "Se generó la imagen");
                        Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\0.jpg");
                    }else{
                        JOptionPane.showMessageDialog(this, "Ingrese las capas a graficar");
                    }
                    break;

                case 4:
                    
                    
                    //int ide = Integer.parseInt(imagen_id_text.getText());
                    //int ide = Integer.parseInt(imagen_id_text.getText());
                    
                    if(!"".equals(imagen_id_text.getText())){
                        
                        
                        int ide = Integer.parseInt(imagen_id_text.getText());
                    
                        Nodo_AVL nuevo = usuario.imagenes.buscar(ide);
                        if (nuevo != null){
                            ABB arbol = nuevo.imagen.capas;
                            //Matriz_pixeles p = arbol.recorrido_Amplitud();
                            //Creador_img q = new Creador_img(p);

                            
                            
                            
                        
                            arbol.crear_grafo(arbol.raiz);
                            String dtox = arbol.imprimir();
                            Creador_img genx = new Creador_img(dtox);
                            //String dto = usuario.capas.crear_grafo(usuario.capas.raiz);
                            //Creador_img cre = new Creador_img(dto);
                            JOptionPane.showMessageDialog(this, "Se generó la imagen");
                            Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\1.jpg");
                            //Actualizar_img(Label_img,"src/imagenes/0.png");
                    }else{
                        JOptionPane.showMessageDialog(this, "Ingrese la imagen a graficar");
                        }
                    
                    }  break;
                    
                case 5:
                    
                    Creador_img w = new Creador_img(usuario.albumes);
                    
                    JOptionPane.showMessageDialog(this, "Se generó la imagen");
                            Actualizar_img(Label_img,"C:\\Users\\usuario\\Desktop\\provisional\\imagenes\\0.jpg");
                    
                    
                    break;
                    
                    
            }
            
            
        
        
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una opción");
        }
        
        
        
    }//GEN-LAST:event_Boton_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void Actualizar_img(JLabel Label_img, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(Label_img.getWidth(),Label_img.getHeight(),Image.SCALE_DEFAULT));//Convirtiendo la imagen a un icóno para poder ponerlo en el label
        // alto de la imagen, ancho de la imagen, algoritmo de escalamiento de la imagen
        Label_img.setIcon(this.icono);
        this.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_enviar;
    private javax.swing.JComboBox<String> Cedes;
    private javax.swing.ButtonGroup Grupo_botones;
    private javax.swing.JComboBox<String> Mensajeros;
    private javax.swing.JPanel Panel_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
