/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package f2_proyecto_estructuras;

import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Pantalla_Cliente extends javax.swing.JFrame {
    
    private ImageIcon imagen;
    private Icon icono;
    
    int opcion = -1;
    String tipo_recorrido = "";

    /**
     * Creates new form Pantalla_Cliente
     */
    Usuario usuario;
    public Pantalla_Cliente(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones_grupo = new javax.swing.ButtonGroup();
        Panel_superior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton_capas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Boton_imgs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Boton_album = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Panel_visualizacion = new javax.swing.JPanel();
        Label_img = new javax.swing.JLabel();
        Panel_generar_img = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        boton_por_imagen = new javax.swing.JRadioButton();
        Boton_por_capa = new javax.swing.JRadioButton();
        boton_ecorrido = new javax.swing.JRadioButton();
        Boton_generar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tipo_recorrido = new javax.swing.JComboBox<>();
        cantidad_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        imagen_id_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel1.setText("Carga Masiva");

        Boton_capas.setText("Capas");
        Boton_capas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_capasActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Boton_imgs.setText("Imágenes");

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel2.setText("Otras Opciones");

        Boton_album.setText("Álbumes");

        jButton3.setText("Ver estructuras");

        javax.swing.GroupLayout Panel_superiorLayout = new javax.swing.GroupLayout(Panel_superior);
        Panel_superior.setLayout(Panel_superiorLayout);
        Panel_superiorLayout.setHorizontalGroup(
            Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_superiorLayout.createSequentialGroup()
                        .addComponent(Boton_capas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_imgs, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_album, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(141, 141, 141)
                .addGroup(Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(Panel_superiorLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        Panel_superiorLayout.setVerticalGroup(
            Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(Panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_capas)
                    .addComponent(Boton_imgs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_album, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel_visualizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Panel_visualizacionLayout = new javax.swing.GroupLayout(Panel_visualizacion);
        Panel_visualizacion.setLayout(Panel_visualizacionLayout);
        Panel_visualizacionLayout.setHorizontalGroup(
            Panel_visualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_visualizacionLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(Label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        Panel_visualizacionLayout.setVerticalGroup(
            Panel_visualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_visualizacionLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(Label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel3.setText("Generar Imagenes");

        Botones_grupo.add(boton_por_imagen);
        boton_por_imagen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton_por_imagen.setText("Por imagen");
        boton_por_imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_por_imagenMouseClicked(evt);
            }
        });

        Botones_grupo.add(Boton_por_capa);
        Boton_por_capa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Boton_por_capa.setText("Por capa");
        Boton_por_capa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_por_capaMouseClicked(evt);
            }
        });

        Botones_grupo.add(boton_ecorrido);
        boton_ecorrido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton_ecorrido.setText(" Por recorrido limitado");
        boton_ecorrido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ecorridoMouseClicked(evt);
            }
        });
        boton_ecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ecorridoActionPerformed(evt);
            }
        });

        Boton_generar.setText("Generar");
        Boton_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_generarActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de recorrido");

        jLabel5.setText("Cantidad de capas");

        Tipo_recorrido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PreOrden", "InOrden", "PostOrden" }));
        Tipo_recorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_recorridoActionPerformed(evt);
            }
        });

        cantidad_text.setText("0");

        jLabel6.setText("Imagen a graficar");

        jLabel7.setText("Capas a graficar");

        javax.swing.GroupLayout Panel_generar_imgLayout = new javax.swing.GroupLayout(Panel_generar_img);
        Panel_generar_img.setLayout(Panel_generar_imgLayout);
        Panel_generar_imgLayout.setHorizontalGroup(
            Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_por_imagen)
                            .addComponent(boton_ecorrido)
                            .addComponent(Boton_por_capa)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_generar_imgLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(imagen_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_generar_imgLayout.createSequentialGroup()
                                    .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cantidad_text, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tipo_recorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        Panel_generar_imgLayout.setVerticalGroup(
            Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_generar_imgLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(boton_ecorrido)
                .addGap(18, 18, 18)
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidad_text, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tipo_recorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(boton_por_imagen)
                .addGap(18, 18, 18)
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(imagen_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Boton_por_capa)
                .addGap(18, 18, 18)
                .addGroup(Panel_generar_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(Boton_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_generar_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Panel_visualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_generar_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_visualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ecorridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_ecorridoActionPerformed

    private void Boton_capasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_capasActionPerformed
        // CARGA MASIVA CAPAS
        Lector_capas lector = new Lector_capas("C:\\Users\\usuario\\Documents\\Byron\\7mo semestre\\Estructuras\\Lab\\Ejemplos aux\\EDD_1S_2022-main\\EntradasFase2\\ImagenSonic\\ImagenSonic.json");
        lector.Lectura(usuario);
        usuario.capas.crear_grafo(usuario.capas.raiz);
        usuario.capas.imprimir();
        Matriz_pixeles d = usuario.capas.recorrido_Preorden(2);
        Creador_img f = new Creador_img(d);
        
        
        
        
        //ABB arbol = usuario.capas;
        //arbol.crear_grafo(arbol.raiz);
        //arbol.imprimir();
    }//GEN-LAST:event_Boton_capasActionPerformed

    private void boton_ecorridoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ecorridoMouseClicked
        //Código del radio button
        opcion = 1;
    }//GEN-LAST:event_boton_ecorridoMouseClicked

    private void boton_por_imagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_por_imagenMouseClicked
        // TODO del por imagen
        opcion = 2;
    }//GEN-LAST:event_boton_por_imagenMouseClicked

    private void Boton_por_capaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_por_capaMouseClicked
        // TODO add your handling code here:
        opcion = 3;
    }//GEN-LAST:event_Boton_por_capaMouseClicked

    private void Boton_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_generarActionPerformed
        Tipo_recorridoActionPerformed(evt);
        System.out.println(tipo_recorrido);
        System.out.println(opcion);
        
        if (opcion == -1){
            JOptionPane.showMessageDialog(this, "Seleccione una opción");
        }else{
            
            switch(opcion){
                
                
                case 1: // Recorrido por límite
                    int cantidad = Integer.parseInt(cantidad_text.getText());
                    System.out.println("vvv"+cantidad);
                    System.out.println(usuario.capas.num_nodos);
                    if (cantidad <= usuario.capas.num_nodos){ 
                        
                    switch (tipo_recorrido) {
                        case "PreOrden":
                            Matriz_pixeles d = usuario.capas.recorrido_Preorden(cantidad);
                            Creador_img f = new Creador_img(d);
                            break;
                        case "InOrden":
                        
                            Matriz_pixeles e = usuario.capas.recorrido_Inorden(cantidad);
                            Creador_img g = new Creador_img(e);
                        
                        
                            break;
                        case "PostOrden":
                            Matriz_pixeles l = usuario.capas.recorrido_Postorden(cantidad);
                            Creador_img h = new Creador_img(l);
                        
                        
                            break;
                        
                        
                        default:
                            break;
                        }
                        
                    this.Actualizar_img(Label_img,"src/imagenes/0.png");
                        
                        
                        
                    
                    }else{
                       JOptionPane.showMessageDialog(this, "El número de capas excede a las capas registradas");      
                    }
                    
                    
                    break;
                case 2:
                    break;
                case 3:
                    break;
                    
            }
        
        }
        
        
    }//GEN-LAST:event_Boton_generarActionPerformed

    private void Tipo_recorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_recorridoActionPerformed
        // para poder sacar lo del combo box
        tipo_recorrido = Tipo_recorrido.getSelectedItem().toString();  
        //System.out.println(tipo_recorrido);
    }//GEN-LAST:event_Tipo_recorridoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void Actualizar_img(JLabel Label_img, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(Label_img.getWidth(),Label_img.getHeight(),Image.SCALE_DEFAULT));//Convirtiendo la imagen a un icóno para poder ponerlo en el label
        // alto de la imagen, ancho de la imagen, algoritmo de escalamiento de la imagen
        Label_img.setIcon(this.icono);
        this.repaint();
    }
   
    /**
     * @param args the command line arguments
     */
    
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_album;
    private javax.swing.JButton Boton_capas;
    private javax.swing.JButton Boton_generar;
    private javax.swing.JButton Boton_imgs;
    private javax.swing.JRadioButton Boton_por_capa;
    public javax.swing.ButtonGroup Botones_grupo;
    private javax.swing.JLabel Label_img;
    private javax.swing.JPanel Panel_generar_img;
    private javax.swing.JPanel Panel_superior;
    private javax.swing.JPanel Panel_visualizacion;
    private javax.swing.JComboBox<String> Tipo_recorrido;
    private javax.swing.JRadioButton boton_ecorrido;
    private javax.swing.JRadioButton boton_por_imagen;
    private javax.swing.JTextField cantidad_text;
    private javax.swing.JTextField imagen_id_text;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    

}
